---
# This Playbook would deploy the whole mongodb cluster with replication and sharding.

- hosts: all
  roles:
  - role: common

## Create Config Server Replica Set
- hosts: mongoc_servers
  roles:
  - role: mongoc

## Create the Shard Replica Sets
- hosts: mongo_servers
  roles:
  - role: mongod

# Create Shart Server
- hosts: mongos_servers
  roles:
  - role: mongos

# run shading test
- include: shard_test.yml
